stages:
  - lint
  - test

lint-src:
  stage: lint
  image: docker.io/golangci/golangci-lint:v2.3.0
  script:
    - golangci-lint run

test-src:
  stage: test
  image: docker.io/library/golang:1.21
  before_script:
    - go install github.com/didier13150/glsimulator@latest
  script:
    - $HOME/go/bin/glsimulator &
    - go test
    - killall glsimulator
